### ISSUE TITLE
Cannot use fullcontact4j in Google App Engine standard (java 7) environment

### ISSUE THREAD

**Issue by ryanwalker** [fullcontact/fullcontact4j#40]
We're running into a problem using the FullContact Card Reader API sdk in Google App Engine. 
When trying to use it in the java 7 environment, we're getting the following error calling fullContact.sendRequest. This is happening because we are not using Google's specified ThreadFactory.
```
com.infusionsoft.cardreaderapi.resource.CardResource requestCardTranscription: Card upload failed (CardResource.java:61)
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:484)
	at java.security.AccessController.checkPermission(AccessController.java:698)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at com.google.apphosting.runtime.security.CustomSecurityManager.checkPermission(CustomSecurityManager.java:55)
	at com.google.apphosting.runtime.security.CustomSecurityManager.checkAccess(CustomSecurityManager.java:136)
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
	at java.lang.Thread.init(Thread.java:391)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:675)
	at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:572)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:600)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:943)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1383)
	at com.fullcontact.api.libs.fullcontact4j.http.RequestExecutorHandler.sendRequestAsync(RequestExecutorHandler.java:82)
	at com.fullcontact.api.libs.fullcontact4j.FullContactHttpInterface.sendRequest(FullContactHttpInterface.java:84)
	at com.fullcontact.api.libs.fullcontact4j.FullContactHttpInterface.sendRequest(FullContactHttpInterface.java:58)
	at com.fullcontact.api.libs.fullcontact4j.FullContact.sendRequest(FullContact.java:148)
	at com.infusionsoft.cardreaderapi.service.FullContactService.uploadCard(FullContactService.java:57)
	at com.infusionsoft.cardreaderapi.service.CardService.requestCardTranscription(CardService.java:52)
	at com.infusionsoft.cardreaderapi.resource.CardResource.requestCardTranscription(CardResource.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.apphosting.runtime.security.shared.intercept.java.lang.reflect.Method_$1.run(Method_.java:169)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.apphosting.runtime.security.shared.intercept.java.lang.reflect.Method_.privilegedInvoke(Method_.java:165)
	at com.google.apphosting.runtime.security.shared.intercept.java.lang.reflect.Method_.invoke_(Method_.java:123)
	at com.google.apphosting.runtime.security.shared.intercept.java.lang.reflect.Method_.invoke(Method_.java:42)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:927)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:875)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:829)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.infusionsoft.pancakes.guice.ContentLengthFilter.doFilter(ContentLengthFilter.java:37)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at io.buji.pac4j.filter.SecurityFilter$2.adapt(SecurityFilter.java:91)
	at io.buji.pac4j.filter.SecurityFilter$2.adapt(SecurityFilter.java:87)
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:144)
	at io.buji.pac4j.filter.SecurityFilter.doFilter(SecurityFilter.java:87)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:559)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:519)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:489)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:238)
	at java.lang.Thread.run(Thread.java:745)```
This could be resolved if we could specify a ThreadFactory. Has anyone else used the sdk in google ap engine successfully?

**Comment by Xorlev** [comment]
Correct me if I'm wrong, but this doesn't seem to be coming from FullContact4j. We don't use mashape unirest. Instead, this appears to be coming from `at com.infusionsoft.cardreaderapi.client.FirebaseClient.<init>(FirebaseClient.java:25)`

If it is being ultimately caused by FullContact4j, can you provide a stacktrace showing which permissions GAE doesn't allow us to have?

**Comment by ryanwalker** [comment]
Oops I put the wrong error message. I'll update that.

**Comment by ryanwalker** [comment]
I updated it with the correct stack trace.

**Comment by ryanwalker** [comment]
Google specifies very specific ways to create/manage threads: https://cloud.google.com/appengine/docs/standard/java/runtime#threads.

**Comment by Xorlev** [comment]
@ParisMi seems like we could allow a `ThreadFactory` to be passed in via an alternative constructor. Either that, or an entire `Executor`.

**Comment by ParisMi** [comment]
In order to make this lib work with GAE, we'd also need to move to OkHttp3, as that's the first version that has some sort of hacky ability to get Retrofit working in GAE: https://github.com/square/retrofit/issues/1149

**Comment by ParisMi** [comment]
Hmm, I'll evaluate OkHttp3 (which looks to be easy to upgrade to) and let you know soon @ryanwalker.

In the meantime: passing in a `RateLimiterConfig.DISABLED` to the FullContact client will disable all parallelism directly in the client. only OkHttp 2's thread pools would stand in the way of GAE support (and FC4J can be passed a custom configured OkHttp client). So if you can figure out some way to get OkHttp2 to support GAE that might work, right there.

**Comment by ryanwalker** [comment]
Thanks for the quick response @ParisMi and @Xorlev. I'll take a look into that.

**Comment by ryanwalker** [comment]
I don't see a way to use okhttp 2 on GAE. It does a lot of threading that I don't have control over.

**Comment by jentfoo** [comment]
@ryanwalker This might be helpful, it does look like it has some ability to control the threaded execution: 
https://github.com/square/retrofit/issues/1259#issuecomment-230409304

**Comment by ParisMi** [comment]
Just related FC4J 5.0.0 @ryanwalker. If you specify a custom ExecutorService and custom OkHttpClient you should be able to get the behavior you want here.

**Comment by ParisMi** [comment]
Marking this closed due to inactivity -- if further issues occur, please open a new issue.
