### ISSUE TITLE
NeverMind!  Old version of FullContact4J

### ISSUE THREAD

**Issue by IronCrystal** [fullcontact/fullcontact4j#49]
Hello,

I am receiving an error every time I attempt to send a Person Request.  I think it might be related to OkHTTP or Retrofit but I'm not sure.

Java 7

> com.fullcontact.api.libs.fullcontact4j.FullContactException: Unknown reason for exception, see stack trace
	at com.fullcontact.api.libs.fullcontact4j.http.FCRetrofitCallback.failure(FCRetrofitCallback.java:88)
	at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
	at retrofit.Utils$SynchronousExecutor.execute(Utils.java:114)
	at retrofit.CallbackRunnable.run(CallbackRunnable.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at retrofit.Platform$Base$2$1.run(Platform.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: retrofit.RetrofitError: com.squareup.okhttp.OkHttpClient.open(Ljava/net/URL;)Ljava/net/HttpURLConnection;
	at retrofit.RetrofitError.unexpectedError(RetrofitError.java:44)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
	at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
	at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
	at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
	... 4 more
Caused by: java.lang.NoSuchMethodError: com.squareup.okhttp.OkHttpClient.open(Ljava/net/URL;)Ljava/net/HttpURLConnection;
	at com.squareup.okhttp.OkUrlFactory.open(OkUrlFactory.java:44)
	at com.fullcontact.api.libs.fullcontact4j.http.FCUrlClient.openConnection(FCUrlClient.java:70)
	at com.fullcontact.api.libs.fullcontact4j.http.FCUrlClient.execute(FCUrlClient.java:64)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
	... 7 more

**Comment by IronCrystal** [comment]
Forget this!  I was using an old version of FullContact.  This is no longer relevant.
