### ISSUE TITLE
CardReader Api crash the Application

### ISSUE THREAD

**Issue by sid180** [fullcontact/fullcontact4j#50]
After executing below line the app get crashed;
 FullContact fcClient = FullContact.withApiKey("xxxxxx").httpClient(client).build();

Error Log :
java.lang.NoClassDefFoundError: com.fullcontact.api.libs.fullcontact4j.http.FCUrlClient
                                                                                    at com.fullcontact.api.libs.fullcontact4j.FullContact$Builder.build(FullContact.java:315)
                                                                                    at com.example.ebms.myapplication.Main2Activity$1.onClick(Main2Activity.java:38)
                                                                                    at android.view.View.performClick(View.java:5265)
                                                                                    at android.view.View$PerformClick.run(View.java:21534)
                                                                                    at android.os.Handler.handleCallback(Handler.java:815)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                    at android.os.Looper.loop(Looper.java:207)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5769)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by ParisMi** [comment]
Hey @sid180 . Which version are you using? The latest one is `5.3.1` which may solve your problem.

**Comment by sid180** [comment]
Hi. sorry for the late reply. I am currently using the latest version(5.3.1) and already implemented older version also but no luck. It carshes the app.

**Comment by ParisMi** [comment]
Hmm. I was able to test this locally:

build.gradle:

`compile "com.fullcontact:fullcontact4j:5.3.1"`

and this code:
```
        FullContact fcClient = FullContact.withApiKey("xxxxxx").build();
        fcClient.buildPersonRequest();
```
And it worked just fine. This was not inside of an android app. Also: you should probably not be using this library directly in an app; it requires that you use the API key in the android app itself, which means someone could decompile your android app and get your fullcontact api key.

The error seems to be indicating that the class `FCUrlClient` cannot be loaded (either because it doesn't exist on the classpath or because there was an error loading it). What happens if you run the code:
`FCUrlClient client = new FCUrlClient(null, null);` does the compiler give you an error?

**Comment by sid180** [comment]
unable to sync gradle "com.fullcontact:fullcontact4j:5.3.1" . Please, advice us

**Comment by ParisMi** [comment]
did you add the proper repositories block?
```
    repositories {
        maven {
            url "http://dl.bintray.com/content/fullcontact/fullcontact-oss"
        }
    }
```

**Comment by sid180** [comment]
Working !!Thanks for your support
