### ISSUE TITLE
Exception on basic company domain lookup

### ISSUE THREAD

**Issue by CalebRoyer** [fullcontact/fullcontact4j#56]
I get an exception with a basic company lookup, though in Postman I can get a response fine for the same apiKey and domain:

Gradle Dependency:
compile group: "com.fullcontact", name: "fullcontact4j", version: "5.4.0" 

Code Snippet:
FullContact fullContact = FullContact.withApiKey(apiKey).build();
CompanyRequest companyRequest = fullContact.buildCompanyRequest().domain("westsidebuildingsupply.com").build(); 
ci = fullContact.sendRequest(companyRequest);

Stack Trace:
com.fullcontact.api.libs.fullcontact4j.FullContactException: Unknown reason for exception, see stack trace 

	at com.fullcontact.api.libs.fullcontact4j.http.FCRetrofitCallback.failure(FCRetrofitCallback.java:78)
	at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
	at retrofit.Utils$SynchronousExecutor.execute(Utils.java:114)
	at retrofit.CallbackRunnable.run(CallbackRunnable.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: retrofit.RetrofitError: okhttp3/internal/http/RequestException
	at retrofit.RetrofitError.unexpectedError(RetrofitError.java:44)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
	at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
	at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
	at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
	... 3 more
Caused by: java.lang.NoClassDefFoundError: okhttp3/internal/http/RequestException
	at okhttp3.internal.huc.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:34)
	at okhttp3.OkUrlFactory.open(OkUrlFactory.java:73)
	at okhttp3.OkUrlFactory.open(OkUrlFactory.java:63)
	at com.fullcontact.api.libs.fullcontact4j.http.FCUrlClient.openConnection(FCUrlClient.java:79)
	at com.fullcontact.api.libs.fullcontact4j.http.FCUrlClient.execute(FCUrlClient.java:73)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
	... 6 more
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.http.RequestException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more

**Comment by ParisMi** [comment]
`Caused by: java.lang.NoClassDefFoundError: okhttp3/internal/http/RequestException`

Looks like your build tool didn't include `okhttp` on the classpath. It's definitely included in FC4J's:
```
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.2.0</version>
        </dependency>
```

Perhaps your maven/gradle/etc build file is not including it for some reason? Do you have a specific dependency exclusion somewhere?
